### ISSUE TITLE
Variables & Tick Variables cannot be accessed from eyeHeight (presumably others as well)

### ISSUE THREAD

**Issue by floral-qua-floral** [Gamepiaynmo/CustomModel#15]
I've only tested this with eyeHeight, but I would assume it probably affects boundingBox and maybe others as well.  
The player's eye height cannot be modified based on variables or tick variables. Attempting to load a model where an eye height value references a variable will not successfully update the player's model and will print _Failed to load model pack : For input string "xxx"_, where _xxx_ is just the variable being referenced.

Allowing eyeHeight to refer to variables would be very handy in certain circumstances, such as when one is moving the playermodel's head up or down and wishes for their viewpoint to reflect that. Assuming boundingBox also has this limitation, it would also be useful for that to be able to refer to variables, so that the bounding box can be adjusted to match the changing eye height. I'm not sure if the limitation is an intentional decision or a bug, but either way I'd love to see this possibility opened up if possible.

**Comment by Gamepiaynmo** [comment]
The eye height and bounding box are intended to be static - Yes, you cannot even give them a dynamic value. Letting them be able to change can cause server & client synchronization problems, and in most cases it's not necessary, like most of the entities in minecraft. In general, I think implementing dynamic eye height / bounding box brings more problems than benefits. That's why I decided to make them unchangeable.
